7614 alterar core test
paygoc6/AuauPI pull request #47
Opened 2021-01-06 17:45 UTC by gabriel-reis-silva

Refatorei os testes de rotas do namespace core_test. Pois houve necessidade agora que estamos migrando do atom para o Datomic. 
Deixei alguns testes comentados, pois será necessário criar um novo "find" do Datomic para utilizar os filtros que serão testados depois.

2021-01-06 17:50 UTC, GabrielLazaro approved these changes

2021-01-06 18:07 UTC, romullo-pereira requested changes
Quando rodo "all tests" as modificações no banco em outros ns de test fazem os testes falharem.
Acho que poderíamos deletar e criar o banco novamente na hora de fazer os testes de rota

e se puder retirar os 2 últimos testes da "logic-test" a função ja não é mais pura e os estão falhando

2021-01-06 18:21 UTC, romullo-pereira approved these changes

2021-01-07 12:18 UTC, VMarkz approved these changes

2021-01-07 12:18 UTC, merged