10044 clj test não funcional
paygoc6/AuauPI pull request #56
Opened 2021-02-01 18:02 UTC by VMarkz

Teste estão sendo chamados corretamente agora

2021-02-01 18:40 UTC, gabriel-reis-silva approved these changes

2021-02-02 12:03 UTC, gabriel-reis-silva approved these changes

2021-02-02 12:11 UTC, GabrielLazaro approved these changes

2021-02-03 12:06 UTC, gabriel-reis-silva requested changes
Arrumar conflitos

2021-02-03 12:06 UTC, gabriel-reis-silva commented on src/auaupi/service.clj
> +<<<<<<< HEAD
Acho que são conflitos, podemos retirar isso

2021-02-03 12:24 UTC, romullo-pereira approved these changes

2021-02-03 12:25 UTC, gabriel-reis-silva approved these changes

2021-02-03 12:25 UTC, merged